### ISSUE TITLE
Bed file too short?

### ISSUE THREAD

**Issue by hditt33** [gtamazian/chromosomer#16]
Hi!
I have a created a bed file based on my chromosomer assembly. When I load it together with the new genome assembly in IGV it does not cover the whole chromosomes, i.e. there are parts of different length missing at the end of each chromosome. Is that a bug or am I missing something?

Best,
Hannes

**Comment by gtamazian** [comment]
Hi Hannes!
What do you mean by the new genome assembly? Is it another assembly of the same genome obtained in the different way?

Best,
Gaik

**Comment by hditt33** [comment]
Hi Gaik,
thanks for the quick reply! I mean the chromosomer assembly and I use the bed file of the fragmentmap that was used to created this assembly. The bed file was created using the 'fragmentmapbed' command.

Best,
Hannes

**Comment by gtamazian** [comment]
Hannes,

In general, it may be expected that there will be reference chromosome regions uncovered by the fragments being assembled. Considering your case, I suppose that there were no proper alignments between the fragments and the chromosome ends because telomere regions are usually poorly assembled and contain a lot of gaps hindering the alignment procedure. You may try to modify the alignment parameters or reduce Chromosomer's ration threshold parameter (command-line option **-r** of **chromosomer fragmentmap**) from its default value of 1.2 to 1.1 or 1.05.

Best,
Gaik

**Comment by hditt33** [comment]
Okay, thank you for help!

Best,
Hannes
